server:
  port: 8082

spring:
  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        port: 8719
        #指定sentinel控制台的地址
        dashboard: 101.43.204.168:8858
        client-ip: 192.168.20.20
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'